"""Shared compatibility cadence for isolated supervision acceptance."""

RECONCILIATION_INTERVAL_SECONDS = 30
CONSECUTIVE_OBSERVATIONS = 2
READINESS_WAIT_MILLISECONDS = RECONCILIATION_INTERVAL_SECONDS * 1000
